site_name: Tw-Curator Documentation
repo_url: https://github.com/transferwise/tw-curator
edit_uri: blob/master/docs/
nav:
  - Overview: index.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Contributing: contributing.md