version: 2

references:
  container_config: &container_config
    docker:
      - image: arti.tw.ee/circle_openjdk11
        user: circleci
    resource_class: medium
    environment:
      TERM: vt100
      GRADLE_OPTS: '-Dorg.gradle.console=plain'
  working_directory: &working_directory
    working_directory: ~/tw-curator

jobs:
  build:
    <<: *working_directory
    environment:
      IN_CIRCLE: true
      ZOOKEEPER_TCP_2181: 2181
      TERM: vt100
    docker:
      - image: arti.tw.ee/circle_openjdk11
        user: circleci
      - image: bitnami/zookeeper:3.5.5
        environment:
          ZOO_MY_ID: 1
          ALLOW_ANONYMOUS_LOGIN: "yes"
    steps:
      - checkout
      - restore_cache:
          key: tw-curator-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Assemble jar
          command: ./gradlew assemble --refresh-dependencies --console=plain --no-daemon
      - run:
          name: Make sure tests tmp dir exists
          command: mkdir tests-out
      - run:
          name: Run tests
          command: ./gradlew check --console=plain --no-daemon --stacktrace
      - save_cache:
          paths:
            - ~/.gradle/
          key: tw-curator-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Gather starter test results
          shell: /bin/bash
          command: |
            pushd tw-tkms-starter/build/reports/tests/test && zip -r ~/junit_html.zip * && popd || true
          when: always
      - store_test_results:
          path: ./tw-curator-starter-core/build/test-results/
      - store_artifacts:
          path: ~/junit_html.zip
          when: always          
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  artifacts-publish:
    <<: *working_directory
    <<: *container_config
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/tw-curator
      - restore_cache:
          key: tw-curator-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Set git config
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "TransferWise CircleCI" && git config --global user.email circle@circle.tw.ee
      - run:
          name: Publish artifacts
          command: |
            if ./.circleci/version-changed.sh tw-curator-starter ; then
              ./gradlew pushTag publish --no-daemon --console=plain
            fi

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - artifacts-publish:
          context: artifactory-deploy
          requires:
            - build
          filters:
            branches:
              only:
                - master
